# Generated by Django 5.2.4 on 2025-08-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueEst2025',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(blank=True, null=True)),
                ('date_dt', models.DateField(blank=True, null=True)),
                ('estimate_date', models.DateField(blank=True, null=True)),
                ('frc', models.CharField(blank=True, null=True)),
                ('est_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('hcl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('contr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
            ],
            options={
                'db_table': 'revenue_est_2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueFact',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('date_dt', models.DateTimeField(blank=True, null=True)),
                ('c_agent', models.CharField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, null=True)),
                ('doc', models.CharField(blank=True, null=True)),
                ('division', models.CharField(blank=True, null=True)),
                ('frc', models.CharField(blank=True, null=True)),
                ('nom_g', models.CharField(blank=True, null=True)),
                ('div_frc', models.CharField(blank=True, null=True)),
                ('nom_frc', models.CharField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'revenue_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevenuePlan2025',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(blank=True, null=True)),
                ('date_dt', models.DateField(blank=True, null=True)),
                ('frc', models.CharField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'revenue_plan_2025',
                'managed': False,
            },
        ),
    ]
