# Generated by Django 5.2.4 on 2025-08-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueUsers',
            fields=[
                ('frc', models.CharField(blank=True, null=True)),
                ('user', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('login', models.CharField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'frc_user',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='revenueest2025',
            table='"fin"."revenue_est_2025"',
        ),
    ]
